#!/usr/bin/env ruby

require 'cgi'
require 'json'

DEBUG = ARGV.delete("-v")

if ARGV.length != 2
  STDERR.puts "Usage #{$PROGRAM_NAME} [-v] <username> <password>"
  STDERR.puts "  username and password according to account"
  STDERR.puts "  -v to see debugging info"

  exit 1
end

username = CGI::escape ARGV[0]
password = CGI::escape ARGV[1]

def curl cmd
  if DEBUG
    puts "=" * 20
    puts "Invoking curl:"
    puts "-" * 20
    puts cmd
    out = `#{cmd}`
    puts "^" * 20
    puts "Response:"
    puts "^" * 20
    puts out
    puts "=" * 20
  else
    out = `#{cmd}`
  end

  JSON.parse out
end

# Get the token
curl_cmd_auth = "curl 'https://auth.sunnyportal.com/auth/realms/SMA/protocol/openid-connect/token' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' -H 'Origin: https://ennexos.sunnyportal.com' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://ennexos.sunnyportal.com/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Sec-GPC: 1' --data-raw 'grant_type=password&username=#{username}&password=#{password}&client_id=SPpbeOS' --silent"
sunny_response = curl(curl_cmd_auth)
access_token = sunny_response["access_token"]

# Use the token
component_id = 10039219
url = "https://uiapi.sunnyportal.com/api/v1/widgets/energybalance?componentId=#{component_id}"
curl_cmd_fetch = "curl '#{url}' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0' -H 'Accept: application/json, text/plain, /' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Authorization: Bearer #{access_token}' -H 'Origin: https://ennexos.sunnyportal.com' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://ennexos.sunnyportal.com/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Sec-GPC: 1' --silent"

sunny_response = curl(curl_cmd_fetch)
puts sunny_response["totalGeneration"]

# Graceful exit
exit 1
